### PR TITLE
Fix/add handle description

### LINKED ISSUE #320: Explain what a handle is in create account screen and main tab

### PR DESCRIPTION
**Pull request by AlexandroHattoum**
### Overview
This PR adds a handle description to help users understanding what a handle is. The modifications happen in `MainTab.kt` and `CreateAccountScreen.kt`. 

### UI details
I've added an question mark icon within the handle input field. Upon click, a small toast appears explaining what a handle is to users. The toast can be dismissed through the `X` icon or by clicking again the question mark icon.

Demo:

https://github.com/user-attachments/assets/1155d373-5150-4e0f-986c-2b1a61d6d340

### CODE REVIEW

File: app/src/main/java/com/github/meeplemeet/ui/components/CommonComponents.kt [hunk 1]
```diff
@@ -590,6 +594,53 @@ fun ConfirmationDialog(
...
+    message: String,
+    onDismiss: () -> Unit,
+    modifier: Modifier = Modifier,
+    testTag: String = CommonComponentsTestTags.CLOSABLE_TOAST,
+    closeButtonTestTag: String = CommonComponentsTestTags.CLOSABLE_TOAST_CLOSE_BUTTON
+) {
+  Surface(
+      modifier = modifier.fillMaxWidth(),
+      color = AppColors.secondary,
+      shape = androidx.compose.foundation.shape.RoundedCornerShape(Dimensions.CornerRadius.medium),
```
Comment (dtbcds) [inline app/src/main/java/com/github/meeplemeet/ui/components/CommonComponents.kt]: Import what you need instead of using the full path.

File: app/src/main/java/com/github/meeplemeet/ui/components/CommonComponents.kt [hunk 2]
```diff
@@ -590,6 +594,53 @@ fun ConfirmationDialog(
   }
 }
 
+/**
+ * A toast that can be closed by clicking on the close icon.
+ *
+ * @param message The message to display.
+ * @param onDismiss Callback when the toast is dismissed.
+ * @param modifier Modifier to be applied to the toast.
```
Comment (dtbcds) [inline app/src/main/java/com/github/meeplemeet/ui/components/CommonComponents.kt:602]: Improve Kdoc, it's missing.

**Review by dtbcds — CHANGES_REQUESTED** [review]
Some kdoc is missing and you have inline imports you should fix.

File: app/src/main/java/com/github/meeplemeet/ui/components/CommonComponents.kt (hunk 2 above)
Comment (AlexandroHattoum) [reply app/src/main/java/com/github/meeplemeet/ui/components/CommonComponents.kt:602]: Fixed in my latest commit.

File: app/src/main/java/com/github/meeplemeet/ui/components/CommonComponents.kt (hunk 1 above)
Comment (AlexandroHattoum) [reply app/src/main/java/com/github/meeplemeet/ui/components/CommonComponents.kt]: Done. Thank you for remarking that.

**Review by dtbcds — APPROVED** [review]
LGTM, ready to be merged!
