### PR TITLE
Fix/UI changes

### LINKED ISSUE #66: Implement the UI changes

### PR DESCRIPTION
**Pull request by NilSamaha**
# PR: UI & Logic Refactor for AddSessionScreen, SessionViewer, and Other Screens

## Summary
This PR refactors and updates multiple screens to fully align with Figma designs, improves component reuse, and enhances UI consistency across the app. Several logical changes and structural improvements were made for better UX and maintainability.

### AddSessionScreen
- **Layout reorganization**:
  - Editable fields positioned at the top.
  - Sliders and participants section scrollable after 3 rows.
  - Action buttons side by side for easier access.
- **Colors updated** to match `AppColors` instead of default colors.
- **Reused components** from other screens for consistency.
- **Logic adjustments** to reflect the new layout and scrolling behavior.

### SessionViewer
- Align structure with Figma for both **edit** and **view** modes.
- **Edit mode** mirrors AddSessionScreen layout for consistency.
- **View mode**: centered session title, underlined game header, centered leave button.
- Refactor components and layout to improve readability and reusability.
- Fix failing tests caused by previous structural changes.
- Adjust logic and component usage to match new structure.
- Ensure colors, spacing, and typography are consistent with app design guidelines.

### Other Screens (by AlexandroHattoum)
- **AddDiscussionScreen**: Changed layout to be more spaced; aligned buttons (with icons) in a row rather than a centered column.
- **DiscussionsOverview**: Changed FAB shape to circular; made screen use custom material theme.
- **SignIn & SignUpScreen**: Updated to use colors from material theme; added icons to buttons.
- **CreateAccountScreen**: Updated to use app logo and colors; improved spacing.
- **Navigation**: Updated navigation to use the custom material theme.

## Impact
- UI fully matches Figma designs for session creation, editing, and viewing.
- Improved scroll and layout behavior on AddSessionScreen.
- Consistent look and feel across multiple screens.
- Cleaner, maintainable, and reusable code.

### CODE REVIEW

File: app/src/main/java/com/github/meeplemeet/ui/AddSessionScreen.kt [hunk 1]
```diff
@@ -152,38 +151,21 @@ fun AddSessionScreen(
...
-                        Icons.AutoMirrored.Filled.ArrowBack,
-                        contentDescription = "Back",
-                        tint = MaterialTheme.colorScheme.onPrimary)
-                  }
-            },
-            colors =
-                TopAppBarDefaults.centerAlignedTopAppBarColors(
-                    containerColor = MaterialTheme.colorScheme.surface))
+        TopBarWithDivider(
+            text = "Create View",
```
Comment (dtbcds) [inline app/src/main/java/com/github/meeplemeet/ui/AddSessionScreen.kt:190]: "Create view" does not seem like the appropriate title for this screen, I think you meant "create session".

File: app/src/main/java/com/github/meeplemeet/ui/AddSessionScreen.kt [hunk 2]
```diff
@@ -198,28 +180,28 @@ fun AddSessionScreen(
...
-                  onValueChange = { form = form.copy(title = it) },
-                  placeholder = TITLE_PLACEHOLDER,
-                  singleLine = true,
-                  modifier =
-                      Modifier.fillMaxWidth().testTag(SessionCreationTestTags.FORM_TITLE_FIELD))
-
-              // Game search
-              GameSearchBar(
+              // Organisation section
+              OrganisationSection(
```
Comment (dtbcds) [inline app/src/main/java/com/github/meeplemeet/ui/AddSessionScreen.kt:208]: While perhaps necessary, your composable `Organization section` takes too many parameters. There's surely a way to maintain the same functionalities and changes you've implemented with less parameters.

File: app/src/main/java/com/github/meeplemeet/ui/SessionDetailsScreen.kt [hunk 3]
```diff
@@ -198,7 +201,7 @@ fun SessionDetailsScreen(
                     requester = account,
                     discussion = discussion,
                     name = form.title,
-                    gameId = form.proposedGame, // game?.uid ?: "Loading...",
+                    gameId = form.proposedGameString, // game?.uid ?: "Loading...",
```
Comment (dtbcds) [inline app/src/main/java/com/github/meeplemeet/ui/SessionDetailsScreen.kt]: Remove these leftover comments, they stem from debugging that wasn't fully cleaned up.

File: app/src/main/java/com/github/meeplemeet/ui/SessionDetailsScreen.kt [hunk 4]
```diff
@@ -254,42 +248,44 @@ fun SessionDetailsScreen(
...
-          OrganizationSection(form, onFormChange = { form = it }, editable = isCurrUserAdmin)
-
           Spacer(Modifier.height(4.dp))
+          Row(
+              horizontalArrangement = Arrangement.spacedBy(12.dp, Alignment.CenterHorizontally),
+              modifier = Modifier.fillMaxWidth(),
+              verticalAlignment = Alignment.CenterVertically) {
+                OutlinedButton(
+                    onClick = {
+                      onBack()
```
Comment (dtbcds) [inline app/src/main/java/com/github/meeplemeet/ui/SessionDetailsScreen.kt]: onBack() called twice for no apparent reason. If there's a specific reason for this double call, consider adding a comment to explain why.

**Review by dtbcds — APPROVED** [review]
### Overall
-  Solid UI changes, they make our screens look more like a unified app instead of a weird reunion of screens. 
- Code is clean, nothing else to say for this part.
- I've left some comments across the files, they're mostly nitpicks or code/comments that stem previous debugging sessions.
- Documentation wise, I think you'd benefit from editing some KDocs for the composables that have gotten their signatures changed.
