### PR TITLE
Add Discussion Model and Messaging System + fix CI

### LINKED ISSUE #1: Message and Discussion models
Create the Message and Discussion models and test them.
Integrate them with Firebase

### PR DESCRIPTION
**Pull request by AntoineBastide47**
## Summary

This PR implements a complete messaging platform with real-time capabilities for the Meeple Meet application. The implementation includes discussion management, account system, and live message synchronization.

It also fixes the CI so that all firebase tests can be run on the CI correctly.

## Key Features
  - Discussion Management: Create, update, and manage chat discussions with participant and admin roles
  - Account System: Complete user account management with basic profile operations
  - Real-time Messaging: Live message updates using Firestore listeners and Kotlin Flows
  - Message Previews: Lightweight discussion previews with unread count tracking
  - Permission System: Role-based access control for admin-only operations

## Technical Implementation
  - Data Layer: Firestore repository with reactive listeners and CRUD operations
  - Architecture: Clean MVVM pattern with StateFlow for reactive UI updates
  - Testing: Comprehensive integration tests with Firestore emulator support
  - Documentation: Complete KDoc documentation throughout the codebase

## Files Added
  - Data models: Account, Discussion, Message, DiscussionPreview
  - Repository layer: FirestoreRepository with reactive capabilities
  - ViewModel: FirestoreViewModel with StateFlow management
  - Exception handling: Custom exceptions for different error cases
  - Test suite: Integration tests covering all functionality

## Test Plan
  - Discussion CRUD operations work correctly
  - Account management functions properly
  - Real-time message updates sync across participants
  - Permission validation prevents unauthorized actions
  - Message previews update with unread counts
  - Firestore emulator integration tests pass

  This establishes the foundation for the messaging feature in Meeple Meet.

### CODE REVIEW

File: app/src/main/java/com/github/meeplemeet/model/Exceptions.kt
Comment (Atomium90) [inline app/src/main/java/com/github/meeplemeet/model/Exceptions.kt:1]: Very good idea to add custom exceptions, but you could add the custom message directly at this level, instead of calling *throw DiscussionNotFoundException("Discussion not found.")* each time you need to throw those customs exceptions.

File: app/src/main/java/com/github/meeplemeet/model/structures/Account.kt [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+/**
+ * Represents a user account stored in Firestore.
+ *
+ * @property uid Globally unique identifier of the account (Firestore document ID).
+ * @property name Human-readable name of the account.
+ * @property previews Map of discussion previews keyed by discussion ID. Each preview stores
+ *   lightweight metadata (e.g. last message, unread count) for discussions this account
+ *   participates in.
+ */
+data class Account(
```
Comment (Atomium90) [inline app/src/main/java/com/github/meeplemeet/model/structures/Account.kt:14]: Just to confirm: is this `Account` model meant to be specific to the discussion module, 
or will it later represent a more general user account with extra attributes?

File: app/src/main/java/com/github/meeplemeet/model/structures/Discussion.kt [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+ *
+ * @property uid Globally unique identifier of the discussion (Firestore document ID).
+ * @property name Human-readable title of the discussion.
+ * @property description Optional textual description of the discussion.
+ * @property messages Ordered list of messages sent in the discussion.
+ * @property participants List of account UIDs participating in this discussion.
+ * @property admins List of account UIDs with administrative privileges in this discussion.
+ * @property createdAt Timestamp indicating when the discussion was created.
+ */
+data class Discussion(
```
Comment (Atomium90) [inline app/src/main/java/com/github/meeplemeet/model/structures/Discussion.kt:17]: Do admins also appear in the `participants` list, or are these two lists mutually exclusive?
If they overlap, this could introduce data duplication (and potentially more complex updates) in Firestore ?

File: app/src/main/java/com/github/meeplemeet/model/structures/Message.kt [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+ * Represents a single message within a discussion.
+ *
+ * Stored inside the `messages` list of a [Discussion] document.
+ *
+ * @property senderId UID of the account that sent this message.
+ * @property content Text body of the message.
+ * @property createdAt Timestamp of when the message was created on the server.
+ */
+@Serializable
+data class Message(
```
Comment (Atomium90) [inline app/src/main/java/com/github/meeplemeet/model/structures/Message.kt:16]: Just wondering: would `content` stay as a plain string, or do you plan to switch to a dedicated message content model later (e.g., for images, attachments, etc.)?

File: app/src/main/java/com/github/meeplemeet/model/systems/FirestoreRepository.kt [hunk 4]
```diff
@@ -0,0 +1,267 @@
...
+  }
+
+  /** Update a discussion's description. */
+  suspend fun setDiscussionDescription(id: String, name: String): Discussion {
+    discussions.document(id).update(Discussion::description.name, name).await()
+    return getDiscussion(id)
+  }
+
+  /** Delete a discussion document. */
+  suspend fun deleteDiscussion(id: String): Discussion {
```
Comment (Atomium90) [inline app/src/main/java/com/github/meeplemeet/model/systems/FirestoreRepository.kt]: This function deletes the Firestore document and then calls `getDiscussion(id)`.
But since the document no longer exists, `getDiscussion()` will throw `DiscussionNotFoundException` ?

File: app/src/main/java/com/github/meeplemeet/model/systems/FirestoreRepository.kt [hunk 5]
```diff
@@ -0,0 +1,267 @@
...
+   */
+  suspend fun sendMessageToDiscussion(
+      discussion: Discussion,
+      sender: Account,
+      content: String
+  ): Discussion {
+    val message = Message(sender.uid, content)
+    discussions
+        .document(discussion.uid)
+        .update(Discussion::messages.name, FieldValue.arrayUnion(message))
```
Comment (Atomium90) [inline app/src/main/java/com/github/meeplemeet/model/systems/FirestoreRepository.kt]: Appending messages directly to an array in Firestore could quickly hit document size limits if discussions become large.
Did you consider storing messages in a subcollection maybe ?

File: app/src/main/java/com/github/meeplemeet/model/systems/FirestoreRepository.kt [hunk 6]
```diff
@@ -0,0 +1,267 @@
...
+        .await()
+
+    discussion.participants.forEach { userId ->
```
Comment (Atomium90) [inline app/src/main/java/com/github/meeplemeet/model/systems/FirestoreRepository.kt:156]: Updating each participant’s preview one by one could cause **N** Firestore writes per message.

File: app/src/main/java/com/github/meeplemeet/model/viewmodels/FirestoreViewModel.kt [hunk 7]
```diff
@@ -0,0 +1,226 @@
...
+      changeRequester: Account,
+      description: String
+  ): Discussion {
+    if (discussion.admins.contains(changeRequester.uid))
+        return repository.setDiscussionDescription(discussion.uid, description)
+    throw PermissionDeniedException("Only discussion admins can perform this operation")
+  }
+
+  /** Delete a discussion (admin-only). */
+  suspend fun deleteDiscussion(discussion: Discussion, changeRequester: Account) {
```
Comment (Atomium90) [inline app/src/main/java/com/github/meeplemeet/model/viewmodels/FirestoreViewModel.kt:76]: Here the exception is always thrown. You probably miss a return statement

File: app/src/main/java/com/github/meeplemeet/model/viewmodels/FirestoreViewModel.kt [hunk 8]
```diff
@@ -0,0 +1,226 @@
...
+    throw PermissionDeniedException("Only discussion admins can perform this operation")
+  }
+
+  /** Update discussion description (admin-only). */
+  suspend fun setDiscussionDescription(
+      discussion: Discussion,
+      changeRequester: Account,
+      description: String
+  ): Discussion {
+    if (discussion.admins.contains(changeRequester.uid))
```
Comment (Atomium90) [inline app/src/main/java/com/github/meeplemeet/model/viewmodels/FirestoreViewModel.kt]: You always use this if statement, so maybe you could refactor it in a `checkAdmin` function

File: app/src/main/java/com/github/meeplemeet/model/viewmodels/FirestoreViewModel.kt [hunk 9]
```diff
@@ -0,0 +1,226 @@
...
+            "Account: ${account.uid} - ${account.name} is not a part of Discussion: ${discussion.uid} - ${discussion.name}")
+    if (discussion.messages.isEmpty()) return account
+    return repository.readDiscussionMessages(
+        account.uid, discussion.uid, discussion.messages.last())
+  }
+
+  // ---------- Real-time flows ----------
+
+  /** Holds a [StateFlow] of discussion preview maps keyed by account ID. */
+  private val previewStates = mutableMapOf<String, StateFlow<Map<String, DiscussionPreview>>>()
```
Comment (Atomium90) [inline app/src/main/java/com/github/meeplemeet/model/viewmodels/FirestoreViewModel.kt:178]: Not sure but, you’re caching the StateFlow per account ID indefinitely in `previewStates`.
Should we eventually clear it (e.g., on logout) to prevent memory leaks when multiple accounts are observed?

**Review by Atomium90 — APPROVED** [review]
### 💬 Overall Comment
This PR brings a clean and well-structured foundation for the discussion and messaging system.  
It clearly defines the Firestore data layer (repository + view model) and the data models (`Discussion`, `Message`, `DiscussionPreview`, `Account`) in a consistent and extensible way.  
The implementation demonstrates a good grasp of asynchronous data handling with Kotlin coroutines and `Flow`.

---

### ✅ Strong Elements
- **Data Models:**  
  The data classes are simple, coherent, and easy to serialize. Good use of default values, and the naming is clear and self-explanatory.
  
- **Documentation:**  
  Consistent KDoc across all entities. The documentation makes it very easy to understand the intended structure and relationships.

- **ViewModel Logic:**  
  The way the repository and view model are separated, along with the use of cached `Flow`s, shows a strong architectural understanding.

- **Extensibility:**  
  The current setup is flexible enough to later introduce media messages, reactions, or read receipts without a major refactor.

---

### ⚠️ Areas for Improvement
I’ve left comments in several files with questions or small concerns, mostly around:
- Logic consistency (e.g., exception handling in `deleteDiscussion()`)
- Potential duplication between `admins` and `participants` lists
- Future scalability for message `content` types (text, image, etc.)
- Minor suggestions to reduce repetition and improve clarity

Please take a look at them and let me know if I misunderstood anything.

---

### 🧪 Tests
The integration test suite is impressive — it provides broad and deep coverage of Firestore-based logic.

**Highlights:**
- Covers all essential flows: account lifecycle, discussions, roles, messaging, and real-time listeners.
- Makes great use of Firestore emulators and shared setup through `FirestoreTests`.
- Asynchronous testing with `runTest` and `Flow` handling is well executed and reliable.

**Possible improvements:**
- Naming could be slightly refined to improve readability (e.g., `non_admin_cannot_delete_discussion`).
- Adding a test for message ordering and multi-user read synchronization would make the coverage truly exhaustive.

Overall, the test layer is robust, realistic, and validates both the correctness and reactivity of the Firestore integration.


---

### 🏁 Conclusion
This PR is a solid step forward toward a robust and maintainable Firestore-based chat system.  
With a few small refinements based on the comments, it’ll be even stronger.  
Great work — clean, thoughtful, and easy to build upon!

File: app/src/main/java/com/github/meeplemeet/model/structures/Account.kt (hunk 1 above)
Comment (AntoineBastide47) [reply app/src/main/java/com/github/meeplemeet/model/structures/Account.kt:14]: This is the basis for the general purpous Account struct for the app.

File: app/src/main/java/com/github/meeplemeet/model/structures/Discussion.kt (hunk 2 above)
Comment (AntoineBastide47) [reply app/src/main/java/com/github/meeplemeet/model/structures/Discussion.kt:17]: They apply in both for precaussion. But this can be changed.

**Comment by Atomium90** [comment]
Reviewers are indeed us, but the person who created the PR and the code should be the assignee, aka you. It's why I changed that.

File: app/src/main/java/com/github/meeplemeet/model/structures/Message.kt (hunk 3 above)
Comment (AntoineBastide47) [reply app/src/main/java/com/github/meeplemeet/model/structures/Message.kt:16]: That would just require an new field:
attachement: Image | Video

File: app/src/main/java/com/github/meeplemeet/model/systems/FirestoreRepository.kt (hunk 4 above)
Comment (AntoineBastide47) [reply app/src/main/java/com/github/meeplemeet/model/systems/FirestoreRepository.kt]: My bad, I will fix it.

File: app/src/main/java/com/github/meeplemeet/model/viewmodels/FirestoreViewModel.kt (hunk 9 above)
Comment (AntoineBastide47) [reply app/src/main/java/com/github/meeplemeet/model/viewmodels/FirestoreViewModel.kt:178]: There is a clear function bellow: previewRemoveFlow for that

File: app/src/main/java/com/github/meeplemeet/model/viewmodels/FirestoreViewModel.kt (hunk 7 above)
Comment (AntoineBastide47) [reply app/src/main/java/com/github/meeplemeet/model/viewmodels/FirestoreViewModel.kt:76]: i will fix this oversight

File: app/src/main/java/com/github/meeplemeet/model/systems/FirestoreRepository.kt (hunk 6 above)
Comment (AntoineBastide47) [reply app/src/main/java/com/github/meeplemeet/model/systems/FirestoreRepository.kt:156]: I will batch these

File: app/src/main/java/com/github/meeplemeet/model/systems/FirestoreRepository.kt (hunk 5 above)
Comment (AntoineBastide47) [reply app/src/main/java/com/github/meeplemeet/model/systems/FirestoreRepository.kt]: For now, as we only store text, 1MB will be sufficient for 99% of discussions. In the future, when adding attachements, we might need to look at this.

**Comment by Atomium90** [comment]
Thanks for your changes. It's all good for me!
